version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: shift
      POSTGRES_PASSWORD: shift
      POSTGRES_DB: shift_db
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
